apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.mongo_e_name }}-deployment"
  labels:
    app: "{{ .Values.mongo_e_name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.mongo_e_name }}"
      tier: backend
  template:
    metadata:
      labels:
        app: "{{ .Values.mongo_e_name }}"
        tier: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mongo-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: "{{ .Values.mongo_e_name }}"
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url


---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.mongo_e_name }}-service"
spec:
  selector:
    app: "{{ .Values.mongo_e_name }}"
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000

