apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ .Values.mongo_name }}-deployment"
  labels:
    app: "{{ .Values.mongo_name }}"
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.mongo_name }}"
      tier: backend
  template:
    metadata:
      labels:
        app: "{{ .Values.mongo_name }}"
        tier: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mongo-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: "{{ .Values.mongo_name }}"
        image: "{{ .Values.deployment.mongo_image }}:{{ .Values.deployment.mongo_tag }}"
        ports: 
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-root-password
        
---
apiVersion: v1
kind: Service
metadata:
  name:  "{{ .Values.mongo_name }}-service"
spec:
  selector:
    app: "{{ .Values.mongo_name }}"
    tier: backend
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
