apiVersion: v2
name: mongo-mongoex-app
description: A Helm chart for Kubernetes
home: https://helm.sh/helm
sources:
  - https://github.com/helm/helm
type: application
maintainers:
  - email: fractiunate@gmail.com
    name: David Rahäuser
version: "0.1.6"
appVersion: "1.16.0"
